local hero = hash("hero")

function init(self)
	--particlefx.play("#fx")
	--particlefx.set_constant("#fx", "emitter", "tint", vmath.vector4(1))
	--sprite.set_constant("#sprite", "tint", vmath.vector4(1))
end


function on_message(self, message_id, message, sender)
	if message_id == COLLISION and message.other_group == hero then
		LEVEL = LEVEL + 1
		if LEVEL > 12 then
			LEVEL = 0				-- get back to beginning
		end
		msg.post(MAIN, "load_level", { lvl = LEVEL })
	end
end